# Generated by Django 4.2.6 on 2023-10-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ARS', 'Arsenal FC'), ('AST', 'Aston Villa FC'), ('BOU', 'AFC Bournemouth'), ('BRE', 'Brentford FC'), ('BRI', 'Brighton & Hove Albion FC'), ('CHE', 'Chelsea FC'), ('CRY', 'Crystal Palace FC'), ('EVE', 'Everton FC'), ('FUL', 'Fulham FC'), ('LEE', 'Leeds United FC'), ('LEI', 'Leicester City FC'), ('LIV', 'Liverpool FC'), ('MCI', 'Manchester City FC'), ('MUN', 'Manchester United FC'), ('NEW', 'Newcastle United FC'), ('NOT', 'Nottingham Forest FC'), ('SOU', 'Southampton FC'), ('TOT', 'Tottenham Hotspur FC'), ('WHU', 'West Ham United FC'), ('WOL', 'Wolverhampton Wanderers FC')], max_length=255)),
                ('league', models.CharField(choices=[('EPL', 'English Premier League'), ('LGA', 'LaLiga'), ('MLS', 'Major League Soccer'), ('BUN', 'Bundesliga'), ('SRA', 'Serie A'), ('LG1', 'Ligue 1')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('strikes', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('CB', 'Center Back'), ('RCB', 'Right Center Back'), ('LCB', 'Left Center Back'), ('RWB', 'Right Wing Back'), ('LWB', 'Left Wing Back'), ('CM', 'Center Mid'), ('CDM', 'Center Defensive Mid'), ('CAM', 'Center Attacking Mid'), ('RCM', 'Right Center Mid'), ('LCM', 'Left Center Mid'), ('RM', 'Right Mid'), ('LM', 'Left Mid'), ('RW', 'Right Winger'), ('LW', 'Left Winger'), ('ST', 'Striker')], max_length=3)),
                ('nationality', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('ALG', 'Algeria'), ('AND', 'Andorra'), ('ANG', 'Angola'), ('ANT', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ARU', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas'), ('BAH', 'Bahrain'), ('BAN', 'Bangladesh'), ('BAR', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BER', 'Bermuda'), ('BHU', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BOT', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BUL', 'Bulgaria'), ('BUR', 'Burkina Faso'), ('BDI', 'Burundi'), ('CAB', 'Cabo Verde'), ('CAM', 'Cameroon'), ('CAN', 'Canada'), ('CAY', 'Cayman Islands'), ('CAF', 'Central African Republic'), ('CHA', 'Chad'), ('CHI', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('CGO', 'Congo'), ('COD', 'Democratic Republic of the Congo'), ('COK', 'Cook Islands'), ('CRC', 'Costa Rica'), ('CIV', "Côte d'Ivoire"), ('CRO', 'Croatia'), ('CUB', 'Cuba'), ('CYP', 'Cyprus'), ('CZE', 'Czech Republic'), ('DEN', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('ENG', 'England'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('ETH', 'Ethiopia'), ('FAI', 'Faroe Islands'), ('FIJ', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GAM', 'Gambia'), ('GEO', 'Georgia'), ('GER', 'Germany'), ('GHA', 'Ghana'), ('GIB', 'Gibraltar'), ('GRE', 'Greece'), ('GRL', 'Greenland'), ('GRD', 'Grenada'), ('GUA', 'Guatemala'), ('GUI', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HAI', 'Haiti'), ('HON', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRI', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('KSA', 'Saudi Arabia'), ('KGZ', 'Kyrgyzstan'), ('KWT', 'Kuwait'), ('LAO', 'Laos'), ('LAT', 'Latvia'), ('LBN', 'Lebanon'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('LVA', 'Latvia'), ('MAD', 'Madagascar'), ('MWI', 'Malawi'), ('MLY', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MAR', 'Morocco'), ('MTN', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MOR', 'Morocco'), ('MOZ', 'Mozambique'), ('MYA', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NEP', 'Nepal'), ('NET', 'Netherlands'), ('NCL', 'New Caledonia'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NIR', 'Northern Ireland'), ('NIG', 'Niger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'), ('MKD', 'North Macedonia'), ('NOR', 'Norway'), ('OMA', 'Oman'), ('PAK', 'Pakistan'), ('PAL', 'Palestine'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PAR', 'Paraguay'), ('PER', 'Peru'), ('PHI', 'Philippines'), ('PLW', 'Palau'), ('POL', 'Poland'), ('POR', 'Portugal'), ('PRI', 'Puerto Rico'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('SAU', 'Saudi Arabia'), ('SCO', 'Scotland'), ('SEN', 'Senegal'), ('SER', 'Serbia'), ('SEY', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SIN', 'Singapore'), ('SKN', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('MAF', 'Saint Martin (French part)'), ('SMR', 'San Marino'), ('STP', 'São Tomé and Príncipe'), ('SXM', 'Sint Maarten (Dutch part)'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SOL', 'Solomon Islands'), ('SOM', 'Somalia'), ('RSA', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('SRI', 'Sri Lanka'), ('SUD', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('SWI', 'Switzerland'), ('SYR', 'Syria'), ('TPE', 'Chinese Taipei'), ('TJK', 'Tajikistan'), ('TAN', 'Tanzania'), ('TGA', 'Tonga'), ('TRI', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TCA', 'Turks and Caicos Islands'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('UAE', 'United Arab Emirates'), ('URU', 'Uruguay'), ('USA', 'United States of America'), ('UZB', 'Uzbekistan'), ('VAN', 'Vanuatu'), ('VAT', 'Vatican City'), ('VEN', 'Venezuela'), ('VGB', 'British Virgin Islands'), ('VIR', 'U.S. Virgin Islands'), ('WAL', 'Wales'), ('YEM', 'Yemen'), ('ZAM', 'Zambia'), ('ZIM', 'Zimbabwe')], max_length=255)),
                ('image_url', models.URLField(default='', max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
        ),
    ]
