# Generated by Django 4.2.6 on 2023-11-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='futdb',
            new_name='futdb_id',
        ),
        migrations.RenameField(
            model_name='nation',
            old_name='futdb',
            new_name='futdb_id',
        ),
        migrations.AddField(
            model_name='player',
            name='futdb_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
